window.addEventListener('error', event => console.error('[Attendly]', event.error || event.message)); window.addEventListener('unhandledrejection', event => console.error('[Attendly]', event.reason));
const SNAP_SERVE = { agentId: 920, agentName: 'Nila', demoMode: false };
const RELAY_URL_STORAGE = 'attendly-snapserve-relay-url';
const students = [{ name: 'Aarav Mehta', roll: '08', pname: 'Rakesh Mehta', phone: '8637488905', present: true }, { name: 'Diya Kapoor', roll: '11', pname: 'Neha Kapoor', phone: '8637488905', present: true }, { name: 'Kabir Shah', roll: '14', pname: 'Priya Shah', phone: '8637488905', present: false }, { name: 'Meera Iyer', roll: '18', pname: 'Suresh Iyer', phone: '8637488905', present: true }, { name: 'Rohan Verma', roll: '21', pname: 'Anita Verma', phone: '8637488905', present: false }, { name: 'Sana Khan', roll: '24', pname: 'Nadia Khan', phone: '8637488905', present: false }];
const rows = document.querySelector('#studentRows');
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const getRelayUrl = () => localStorage.getItem(RELAY_URL_STORAGE)?.trim().replace(/\/$/, '') || window.location.origin;
function updateCounts() { const present = students.filter(student => student.present).length, absent = students.length - present; presentCount.textContent = present; absentCount.textContent = absent; totalCount.textContent = students.length; selectedCount.textContent = absent; queueBadge.textContent = `${absent} queued`; attendanceRate.textContent = `${students.length ? Math.round(present / students.length * 100) : 0}% attendance`; progressBar.style.width = `${students.length ? present / students.length * 100 : 0}%`; }
function render() { rows.innerHTML = students.map((student, index) => `<tr><td>${student.name}</td><td>${student.roll}</td><td><button class="status ${student.present ? 'present' : 'absent'}" data-index="${index}">${student.present ? 'Present' : 'Absent'}</button></td></tr>`).join(''); updateCounts(); }
render();
startBtn.addEventListener('click', () => { const record = { date: new Date().toISOString().slice(0, 10), className: classSelect.value, students: students.map(({ name, roll, present }) => ({ name, roll, present })) }; fetch(`${getRelayUrl()}/api/attendance`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(record) }).catch(() => {}); });
rows.onclick = event => { if (event.target.matches('.status')) { students[Number(event.target.dataset.index)].present = !students[Number(event.target.dataset.index)].present; render(); saveState.textContent = '● Saved just now'; } };
async function triggerCall(student) { const relayUrl = getRelayUrl(); const [std, sec] = classSelect.value.split('-'); const payload = { agentId: SNAP_SERVE.agentId, toNumber: student.phone.startsWith('+') ? student.phone : `+91${student.phone}`, variables: { std, sec, studentName: student.name, parentName: student.pname, name: student.name, pname: student.pname, phone: student.phone, language: 'ta-IN', questions: ['Why was the student absent today? Please share the reason?'] } }; if (SNAP_SERVE.demoMode) { await wait(900); return { status: 'completed', callSummary: 'Parent confirmed that the student is unwell.' }; } const created = await fetch(`${relayUrl}/api/calls/outbound`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!created.ok) throw Error(`Call relay failed (${created.status})`); return created.json(); }
startBtn.onclick = async () => { const absent = students.filter(student => !student.present); if (!absent.length) return showToast('Mark at least one student absent first.'); if (!getRelayUrl() && !SNAP_SERVE.demoMode) { settingsDialog.showModal(); showToast('Set the secure relay URL first.'); return; } startBtn.disabled = true; callIntro.classList.add('hidden'); callQueue.classList.remove('hidden'); callQueue.innerHTML = absent.map((student, index) => `<div class="queue-item" id="call-${index}"><div class="avatar">${student.pname.split(' ').map(part => part[0]).join('')}</div><div><strong>${student.pname}</strong><small>Parent of ${student.name} · ${student.phone}</small><p class="reason" id="reason-${index}"></p></div><em>Queued</em></div>`).join(''); for (let index = 0; index < absent.length; index++) { const item = document.querySelector(`#call-${index}`); item.classList.add('calling'); item.querySelector('em').textContent = 'Calling…'; try { const result = await triggerCall(absent[index]), reason = result.callSummary || result.dispositionResult || 'Response received'; item.classList.remove('calling'); item.classList.add('done'); item.querySelector('em').textContent = 'Logged'; item.querySelector('.reason').textContent = `Reason: ${reason}`; item.title = result.transcript || reason; localStorage.setItem(`attendly-call-${absent[index].name}`, JSON.stringify({ student: absent[index].name, parent: absent[index].pname, phone: absent[index].phone, reason, status: result.status, at: new Date().toISOString() })); } catch (error) { item.querySelector('em').textContent = 'Retry needed'; item.querySelector('.reason').textContent = error.message; } } startBtn.disabled = false; startBtn.textContent = 'All calls completed'; queueBadge.textContent = 'Complete'; showToast('Parent responses have been logged.'); };
classSelect.onchange = () => { classLabel.textContent = `Class ${classSelect.value.replace('-', ' · Section ')}`; showToast('Class register loaded.'); };
const dialog = document.querySelector('#studentDialog');
addBtn.onclick = () => dialog.showModal();
closeDialog.onclick = () => dialog.close();
studentForm.onsubmit = event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); students.push({ ...data, present: false }); render(); dialog.close(); event.target.reset(); showToast(`${data.name} added as absent.`); };
settingsLink.onclick = event => { event.preventDefault(); relayUrlInput.value = getRelayUrl(); settingsDialog.showModal(); };
closeSettings.onclick = () => settingsDialog.close();
settingsForm.onsubmit = event => { event.preventDefault(); const relayUrl = relayUrlInput.value.trim().replace(/\/$/, ''); if (relayUrl) localStorage.setItem(RELAY_URL_STORAGE, relayUrl); else localStorage.removeItem(RELAY_URL_STORAGE); settingsDialog.close(); showToast(relayUrl ? 'Secure relay URL saved on this device.' : 'Secure relay URL removed.'); };
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
