const SNAP_SERVE = { apiBase: 'https://app.snapserve.ai/api', agentId: 920, agentName: 'Nila', demoMode: false };
const API_KEY_STORAGE = 'attendly-snapserve-api-key';
const students = [{ name: 'Aarav Mehta', roll: '08', pname: 'Rakesh Mehta', phone: '8637488905', present: true }, { name: 'Diya Kapoor', roll: '11', pname: 'Neha Kapoor', phone: '8637488905', present: true }, { name: 'Kabir Shah', roll: '14', pname: 'Priya Shah', phone: '8637488905', present: false }, { name: 'Meera Iyer', roll: '18', pname: 'Suresh Iyer', phone: '8637488905', present: true }, { name: 'Rohan Verma', roll: '21', pname: 'Anita Verma', phone: '8637488905', present: false }, { name: 'Sana Khan', roll: '24', pname: 'Nadia Khan', phone: '8637488905', present: false }];
const rows = document.querySelector('#studentRows');
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const getApiKey = () => localStorage.getItem(API_KEY_STORAGE)?.trim() || '';
function updateCounts() { const present = students.filter(student => student.present).length, absent = students.length - present; presentCount.textContent = present; absentCount.textContent = absent; totalCount.textContent = students.length; selectedCount.textContent = absent; queueBadge.textContent = `${absent} queued`; attendanceRate.textContent = `${students.length ? Math.round(present / students.length * 100) : 0}% attendance`; progressBar.style.width = `${students.length ? present / students.length * 100 : 0}%`; }
function render() { rows.innerHTML = students.map((student, index) => `<tr><td>${student.name}</td><td>${student.roll}</td><td><button class="status ${student.present ? 'present' : 'absent'}" data-index="${index}">${student.present ? 'Present' : 'Absent'}</button></td></tr>`).join(''); updateCounts(); }
render();
rows.onclick = event => { if (event.target.matches('.status')) { students[Number(event.target.dataset.index)].present = !students[Number(event.target.dataset.index)].present; render(); saveState.textContent = '● Saved just now'; } };
async function triggerCall(student) { const apiKey = getApiKey(); if (!apiKey && !SNAP_SERVE.demoMode) throw Error('Add your SnapServe API key in Settings before starting calls.'); const [std, sec] = classSelect.value.split('-'); const payload = { agentId: SNAP_SERVE.agentId, toNumber: student.phone.startsWith('+') ? student.phone : `+91${student.phone}`, variables: { std, sec, name: student.name, pname: student.pname, phone: student.phone, questions: ['Why was the student absent today? Please share the reason?'] } }; if (SNAP_SERVE.demoMode) { await wait(900); return { status: 'completed', callSummary: 'Parent confirmed that the student is unwell.', dispositionResult: 'Reason received', transcript: `Agent: Why was ${student.name} absent today? Parent: The student is unwell.` }; } const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` }; const created = await fetch(`${SNAP_SERVE.apiBase}/calls/outbound`, { method: 'POST', headers, body: JSON.stringify(payload) }); if (!created.ok) throw Error(`SnapServe call failed (${created.status})`); const call = await created.json(); for (let attempt = 0; attempt < 30; attempt++) { await wait(3000); const response = await fetch(`${SNAP_SERVE.apiBase}/calls/${call.id}`, { headers }); if (!response.ok) continue; const record = await response.json(); if (['completed', 'failed', 'no_pickup', 'busy', 'cancelled'].includes(record.status)) return record; } throw Error('Timed out waiting for call outcome'); }
startBtn.onclick = async () => { const absent = students.filter(student => !student.present); if (!absent.length) return showToast('Mark at least one student absent first.'); if (!getApiKey() && !SNAP_SERVE.demoMode) { settingsDialog.showModal(); showToast('Add your SnapServe API key first.'); return; } startBtn.disabled = true; callIntro.classList.add('hidden'); callQueue.classList.remove('hidden'); callQueue.innerHTML = absent.map((student, index) => `<div class="queue-item" id="call-${index}"><div class="avatar">${student.pname.split(' ').map(part => part[0]).join('')}</div><div><strong>${student.pname}</strong><small>Parent of ${student.name} · ${student.phone}</small><p class="reason" id="reason-${index}"></p></div><em>Queued</em></div>`).join(''); for (let index = 0; index < absent.length; index++) { const item = document.querySelector(`#call-${index}`); item.classList.add('calling'); item.querySelector('em').textContent = 'Calling…'; try { const result = await triggerCall(absent[index]), reason = result.callSummary || result.dispositionResult || 'Response received'; item.classList.remove('calling'); item.classList.add('done'); item.querySelector('em').textContent = 'Logged'; item.querySelector('.reason').textContent = `Reason: ${reason}`; item.title = result.transcript || reason; localStorage.setItem(`attendly-call-${absent[index].name}`, JSON.stringify({ student: absent[index].name, parent: absent[index].pname, phone: absent[index].phone, reason, status: result.status, at: new Date().toISOString() })); } catch (error) { item.querySelector('em').textContent = 'Retry needed'; item.querySelector('.reason').textContent = error.message; } } startBtn.disabled = false; startBtn.textContent = 'All calls completed'; queueBadge.textContent = 'Complete'; showToast('Parent responses have been logged.'); };
classSelect.onchange = () => { classLabel.textContent = `Class ${classSelect.value.replace('-', ' · Section ')}`; showToast('Class register loaded.'); };
const dialog = document.querySelector('#studentDialog');
addBtn.onclick = () => dialog.showModal();
closeDialog.onclick = () => dialog.close();
studentForm.onsubmit = event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); students.push({ ...data, present: false }); render(); dialog.close(); event.target.reset(); showToast(`${data.name} added as absent.`); };
settingsLink.onclick = event => { event.preventDefault(); apiKeyInput.value = getApiKey(); settingsDialog.showModal(); };
closeSettings.onclick = () => settingsDialog.close();
settingsForm.onsubmit = event => { event.preventDefault(); const key = apiKeyInput.value.trim(); if (key) localStorage.setItem(API_KEY_STORAGE, key); else localStorage.removeItem(API_KEY_STORAGE); settingsDialog.close(); showToast(key ? 'API key saved on this device.' : 'API key removed.'); };
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
